# Generated by Django 6.0.4 on 2026-05-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending AI Review'), ('Shortlisted', 'Shortlisted by AI'), ('AI Rejected', 'Rejected by AI'), ('HR Interviewing', 'HR Interviewing'), ('Hired', 'Hired! 🎉'), ('Final Reject', 'Not Selected')], default='Pending', max_length=20),
        ),
    ]
