# Generated by Django 6.0.4 on 2026-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.DateTimeField(blank=True, help_text='Set the date and time for the interview', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_venue',
            field=models.CharField(blank=True, help_text='Zoom link, Google Meet, or physical address', max_length=255, null=True),
        ),
    ]
