# Generated by Django 6.0.4 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_candidatetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Raw text extracted from the PDF for HR keyword searching.', null=True),
        ),
    ]
